let productos = [{ id: 1,  nombre: "Celular Samsung A52", precio: 72000, img: "./img/celulares/CGG_Samsung-Galaxy-A52.jpg"},
                 { id: 2,  nombre: "Celular Samsung A52", precio: 72000, img: "./img/celulares/CGG_Samsung-Galaxy-A52.jpg"},
                 { id: 3,  nombre: "Celular Samsung A52", precio: 72000, img: "./img/celulares/CGG_Samsung-Galaxy-A52.jpg"},
                 { id: 4,  nombre: "Celular Samsung A73", precio: 80000, img: "./img/celulares/CGG_Samsung-Galaxy-A52.jpg"},
                 { id: 5,  nombre: "Celular Samsung A73", precio: 80000, img: "./img/celulares/CGG_Samsung-Galaxy-A52.jpg"},
                 { id: 6,  nombre: "Celular Samsung A73", precio: 80000, img: "./img/celulares/CGG_Samsung-Galaxy-A52.jpg"},
                 { id: 7,  nombre: "Celular Xiaomi Mi 11", precio: 90000, img: "./img/celulares/xiaomi-11t.jpg"},
                 { id: 8,  nombre: "Celular Xiaomi Mi 11", precio: 90000, img: "./img/celulares/xiaomi-11t.jpg"},
                 { id: 9,  nombre: "Celular Xiaomi Mi 11", precio: 90000, img: "./img/celulares/xiaomi-11t.jpg"},
                 { id: 10, nombre: "Celular Xiaomi Mi 11", precio: 90000, img: "./img/celulares/xiaomi-11t.jpg"},
                 { id: 11, nombre: "Celular Xiaomi Mi 11", precio: 90000, img: "./img/celulares/xiaomi-11t.jpg"},
                 { id: 12, nombre: "Celular Xiaomi Mi 11", precio: 90000, img: "./img/celulares/xiaomi-11t.jpg"}];
