let productos = [{ id: 1,  nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda1.jpg"},
                 { id: 2,  nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda1.jpg"},
                 { id: 3,  nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda1.jpg"},
                 { id: 4,  nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda1.jpg"},
                 { id: 5,  nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda1.jpg"},
                 { id: 6,  nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda1.jpg"},
                 { id: 7,  nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda2.jpg"},
                 { id: 8,  nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda2.jpg"},
                 { id: 9,  nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda2.jpg"},
                 { id: 10, nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda2.jpg"},
                 { id: 11, nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda2.jpg"},
                 { id: 12, nombre: "Funda para celular", precio: 1000, img: "./img/fundas/funda2.jpg"}];
